import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
      phoneNumber: 333333333,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
      phoneNumber: 333333333,
    },
  ],
  products: [
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kedi',
      detailcategory:'keee',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d1',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme1111',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kedi',
      detailcategory:'keee2',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d2',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'denemeee',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kedi',
      detailcategory:'keee2',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d3',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme111',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kedi',
      detailcategory:'keee',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d4',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme2',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kopek',
      detailcategory:'golden',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d5',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme3',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kopek',
      detailcategory:'golden',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d6',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme9',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kopek',
      detailcategory:'golden',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d7',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme10',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kopek',
      detailcategory:'pitbul',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d8',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'deneme11',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kopek',
      detailcategory:'pitbul',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d9',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'denem11',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kuş',
      detailcategory:'aaaa',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d10',
    },
    {
      description:'At ilanı',
      ilanTarihi: '23.02.2022',
      fiyat: 'Görüşülür',
      slug: 'denem112',
      irk: 'Golden',
      cinsiyet: 'Erkek',
      age: '2.5',
      ownerUser: 'Murat Yavuz',
      location: 'Erzurum',
      image:'/images/sample.jpeg',
      category:'kuş',
      detailcategory:'aaaa',
      vitrin:'true',
      ilantelNo:'05344332432',
      deneme:'d11',
    },
  ],
};

export default data;
